name: My First Action

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    #paths:
      #- 'data/**.csv'
  pull_request:
    branches: [ main ]

jobs:

  echo-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Variables
        run: |
          printf "username=%s\npassword=%s" ${{ variables.LOGIN_AUTHN }} ${{ secrets.LOGIN_API_KEY }} 

  read-csv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Echo CSV contents
        run: cat data/myfile.csv

  fetch-api:
    runs-on: ubuntu-latest
    needs: read-csv
    steps:
      - name: Curl and echo part of response
        run: |
          RESPONSE=$(curl -s https://api.github.com/repos/${{ github.repository }})
          echo "Full name: $(echo "$RESPONSE" | jq -r '.full_name')"
          echo "Stars: $(echo "$RESPONSE" | jq -r '.stargazers_count')"

