name: Read CSV

on:
  workflow_dispatch:
  push:
    paths:
      - 'data/**.csv'
    branches: [ main ]


jobs:
  read-csv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Echo CSV contents
        run: cat data/myfile.csv



